begin;
set local statement_timeout='15s';
select set_config('request.jwt.claim.sub',(select user_id::text from public.admin_users limit 1),true);
set local role authenticated;
do $$ declare p uuid; rejected boolean; begin
select id into p from public.products limit 1;
insert into public.product_manufacturing_recipes(product_id,data) values(p,'{"kind":"candle","defaults":{"wax_g_per_cc":0.85},"lines":[{"key":"vessel","label":"Envase / frasco","unit":"unit","basis":"fixed","required":true,"default_name":"","default_quantity":1,"purchase":{"unit":"unit","pack_size":null,"density_g_ml":0.9},"name":"Vaso prueba","quantity":1},{"key":"wax","label":"Cera de soja","unit":"g","basis":"wax_capacity","required":true,"default_name":"Cera de soja","default_quantity":null,"purchase":{"unit":"kg","pack_size":null,"density_g_ml":0.9},"name":"Cera de soja","quantity":null},{"key":"catalyst","label":"Estabilizador","unit":"g","basis":"per100wax","required":true,"default_name":"Estabilizador para cera de soja","default_quantity":2.5,"purchase":{"unit":"kg","pack_size":null,"density_g_ml":0.9},"name":"Estabilizador para cera de soja","quantity":2.5},{"key":"fragrance","label":"Fragancia elegida","unit":"ml","basis":"per100wax_ml","required":true,"default_name":"Según fragancia elegida","default_quantity":5,"purchase":{"unit":"ml","pack_size":null,"density_g_ml":0.9},"name":"Según fragancia elegida","quantity":5},{"key":"wick","label":"Pabilo","unit":"cm","basis":"wick_external","required":true,"default_name":"Pabilo","default_quantity":1,"purchase":{"unit":"m","pack_size":null,"density_g_ml":0.9},"triada_quantity":3,"name":"Pabilo","quantity":3},{"key":"tab","label":"Chapita base","unit":"unit","basis":"same_wicks","required":true,"default_name":"Chapita base de pabilo","default_quantity":null,"purchase":{"unit":"unit","pack_size":null,"density_g_ml":0.9},"name":"Chapita base de pabilo","quantity":null},{"key":"pack1","label":"Componente 1","unit":"unit","basis":"fixed","required":false,"default_name":"","default_quantity":null,"purchase":{"unit":"unit","pack_size":null,"density_g_ml":0.9},"group":"presentation","name":"","quantity":null},{"key":"pack2","label":"Componente 2","unit":"unit","basis":"fixed","required":false,"default_name":"","default_quantity":null,"purchase":{"unit":"unit","pack_size":null,"density_g_ml":0.9},"group":"presentation","name":"","quantity":null},{"key":"pack3","label":"Componente 3","unit":"unit","basis":"fixed","required":false,"default_name":"","default_quantity":null,"purchase":{"unit":"unit","pack_size":null,"density_g_ml":0.9},"group":"presentation","name":"","quantity":null},{"key":"pack4","label":"Componente 4","unit":"unit","basis":"fixed","required":false,"default_name":"","default_quantity":null,"purchase":{"unit":"unit","pack_size":null,"density_g_ml":0.9},"group":"presentation","name":"","quantity":null}],"category_id":"00000000-0000-0000-0000-000000000001","template_revision":2,"status":"ready","measures":{"fill_ml":200,"wax_g_per_cc":0.85,"external_height_cm":10}}'::jsonb) on conflict(product_id) do update set data=excluded.data;
rejected:=false;begin update public.product_manufacturing_recipes set data=jsonb_set(data,'{measures,external_height_cm}','null') where product_id=p;exception when raise_exception then rejected:=true;end;if not rejected then raise exception 'FAIL missing external height accepted';end if;
rejected:=false;begin update public.product_manufacturing_recipes set data=jsonb_set(data,'{lines,3,unit}','"g"') where product_id=p;exception when raise_exception then rejected:=true;end;if not rejected then raise exception 'FAIL ml essence treated as grams';end if;
rejected:=false;begin update public.product_manufacturing_recipes set data=jsonb_set(data,'{lines,4,quantity}','1.5') where product_id=p;exception when raise_exception then rejected:=true;end;if not rejected then raise exception 'FAIL fractional wicks';end if;
end $$;
rollback;
select 'PASS: v2 recipe accepted; missing exterior height, wrong essence unit, fractional wicks rejected; rollback' as result;