const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({categoryForm(){},productForm(){},fragForm(){}});
vm.runInContext(fs.readFileSync(__dirname+'/../public/manufacturing.js','utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
assert.equal(run("Mfg.preset('candle').lines.length"),10);
assert.equal(run("Mfg.preset('diffuser').lines.length"),8);
assert.match(run("Mfg.validate({status:'ready',lines:[{name:'Lavanda',percent:80}]},'fragrance').join()"),/100/);
assert.equal(run("Mfg.validate({status:'draft',lines:[{name:'Lavanda',percent:80}]},'fragrance').length"),0);
assert.equal(run("Mfg.validate({status:'ready',lines:[{name:'A',percent:70},{name:'B',percent:30}]},'fragrance').length"),0);
assert.match(run("Mfg.validate({status:'ready',lines:[{name:'LAVÁNDA',percent:50},{name:' lavanda ',percent:50}]},'fragrance').join()"),/repetidas/);
run(`let recipe={kind:'candle',status:'ready',measures:{final_mass_g:112,internal_height_cm:8,wick_allowance_cm:2},lines:Mfg.preset('candle').lines.slice(0,6).map(l=>({...l,name:l.label,quantity:{vessel:1,wax:null,catalyst:2,fragrance:10,wick:2,tab:2}[l.key]}))}`);
assert.ok(Math.abs(run('Mfg.totals(recipe).wax')-100)<1e-9);
assert.equal(run("Mfg.totals(recipe).rows.find(l=>l.key==='wick').total"),20);
assert.equal(run("Mfg.validate(recipe,'product').length"),0);
run("recipe.measures.final_mass_g=100;recipe.lines.forEach(l=>{if(l.basis==='per100wax')l.basis='per100mass'})");
assert.equal(run('Mfg.totals(recipe).wax'),88);
run("recipe.lines.find(l=>l.key==='fragrance').basis='per100wax'");
assert.match(run("Mfg.validate(recipe,'product').join()"),/misma base/);
run("recipe.lines.find(l=>l.key==='fragrance').basis='per100mass';recipe.measures={}");
assert.match(run("Mfg.validate(recipe,'product').join()"),/Falta cantidad/);
run("recipe.status='draft'");assert.equal(run("Mfg.validate(recipe,'product').length"),0);
console.log('PASS: templates, blends, exact percentages, duplicate normalization, wax/mix bases, wick length, missing measures, draft/ready');
